<<<<<<< HEAD
=======
# Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not
# use this file except in compliance with the License. A copy of the License
# is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.
>>>>>>> 40323cc7740e2de2b8eed6a4642b956c55a0a02b
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon Config trigger that finds open S3 Buckets and logs them to SNS.
Resources:
  sduConfigS3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: open_buckets.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: An AWS Config rule that is triggered by S3 Bucket Deployment.
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TOPIC_ARN: !Ref OpenBucketNotifyTopic
      Policies:
         - AWSConfigRulesExecutionRole
         - AmazonS3FullAccess
         - AmazonSNSFullAccess
      Events:
        OpenBucketCloudWatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.config
              detail-type:
                - "Config Rules Compliance Change"
              detail:
                configRuleName:
                  - "s3-bucket-public-write-prohibited"
                  - "s3-bucket-public-read-prohibited"
  OpenBucketNotifyTopic:
    Type: 'AWS::SNS::Topic'
